// Investigation Pipeline - Deterministic 2-hop investigation engine
import { randomUUID } from 'crypto';
import {
  getAddressRisk,
  checkSanctions,
  getAddressInfo,
  getAddressConnections,
  getAddressFundedBy,
  getAddressAssetFlow,
  getAddressBalance,
  getAddressFeatures,
  resetCallCount,
  getCallCount,
} from './range';
import { findPatterns } from './patterns';
import { saveCase, saveConnections, saveFundingSource } from './db';
import { GUARDRAILS } from './constants';
import type { InvestigationResult, Connection, Hop2RiskResult, FundingSource } from '@/types';

export interface InvestigationStep {
  step: string;
  status: 'running' | 'done' | 'error';
  data?: any;
  error?: string;
}

export type StepCallback = (step: InvestigationStep) => void;

/**
 * Run a complete investigation on a blockchain address
 */
export async function runInvestigation(
  address: string,
  network: string,
  onStep?: StepCallback
): Promise<InvestigationResult> {
  const id = randomUUID();
  const timestamp = new Date().toISOString();

  resetCallCount();

  const emitStep = (step: InvestigationStep) => {
    if (onStep) onStep(step);
  };

  try {
    // PARALLEL BATCH 1: Risk triage, sanctions, entity, balance
    emitStep({ step: 'risk_triage', status: 'running' });
    emitStep({ step: 'sanctions_check', status: 'running' });
    emitStep({ step: 'entity_identification', status: 'running' });

    const [risk, sanctions, entity, balance] = await Promise.all([
      getAddressRisk(address, network),
      checkSanctions(address, network, true),
      getAddressInfo(address, network),
      getAddressBalance(address, network),
    ]);

    emitStep({ step: 'risk_triage', status: 'done', data: risk });
    emitStep({ step: 'sanctions_check', status: 'done', data: sanctions });
    emitStep({ step: 'entity_identification', status: 'done', data: entity });

    // PARALLEL BATCH 2: Connections, funding, features
    emitStep({ step: 'connections', status: 'running' });
    emitStep({ step: 'funding_origin', status: 'running' });

    const [connections, fundingOrigin, stats] = await Promise.all([
      getAddressConnections(address, network, GUARDRAILS.MAX_COUNTERPARTIES),
      getAddressFundedBy(address, network),
      getAddressFeatures(address, network),
    ]);

    const resolvedConnections = extractConnections(connections);
    const resolvedFundingOrigin = extractFundingSource(fundingOrigin);

    emitStep({ step: 'connections', status: 'done', data: { ...connections, connections: resolvedConnections } });
    emitStep({ step: 'funding_origin', status: 'done', data: resolvedFundingOrigin });

    // PARALLEL BATCH 3: Asset flow
    emitStep({ step: 'asset_flow', status: 'running' });
    const assetFlow = await getAddressAssetFlow(address, network);
    emitStep({ step: 'asset_flow', status: 'done', data: assetFlow });

    // HOP 2: Risk-scan top counterparties
    emitStep({ step: 'hop2_risk', status: 'running' });

    const topCounterparties = resolvedConnections.slice(0, GUARDRAILS.MAX_HOP2_SCANS);
    const hop2Risks: Hop2RiskResult[] = [];

    if (topCounterparties.length > 0) {
      const hop2Results = await Promise.all(
        topCounterparties.map((conn: any) =>
          getAddressRisk(conn.address, conn.network || network)
        )
      );

      for (let i = 0; i < hop2Results.length; i++) {
        hop2Risks.push({
          address: topCounterparties[i].address,
          riskLevel: hop2Results[i].riskLevel || 'UNKNOWN',
          riskScore: hop2Results[i].riskScore,
        });
      }
    }

    emitStep({ step: 'hop2_risk', status: 'done', data: hop2Risks });

    // PATTERN MATCHING (local, no API)
    emitStep({ step: 'pattern_matching', status: 'running' });
    const patterns = await findPatterns(id, address, resolvedFundingOrigin, resolvedConnections);
    emitStep({ step: 'pattern_matching', status: 'done', data: patterns });

    // Calculate confidence
    const confidence = calculateConfidence(risk, sanctions, stats);

    // Build investigation result
    const result: InvestigationResult = {
      id,
      address,
      network,
      timestamp,
      risk,
      sanctions,
      entity,
      connections: resolvedConnections,
      fundingOrigin: resolvedFundingOrigin,
      assetFlow: assetFlow || null,
      stats: stats || null,
      hop2Risks,
      patterns,
      report: '', // Will be generated by AI later
      apiCallCount: getCallCount(),
      confidence,
    };

    // Save to database
    saveCase(result);

    if (result.connections.length > 0) {
      saveConnections(id, address, result.connections);
    }

    if (result.fundingOrigin?.funderAddress) {
      saveFundingSource(id, address, result.fundingOrigin);
    }

    return result;
  } catch (error: any) {
    console.error('Investigation error:', error);

    // Return partial result on error
    return {
      id,
      address,
      network,
      timestamp,
      risk: { address, network, riskLevel: 'UNKNOWN', error: error.message },
      sanctions: { address, isSanctioned: false, isBlacklisted: false },
      entity: { address },
      connections: [],
      fundingOrigin: null,
      assetFlow: null,
      stats: null,
      hop2Risks: [],
      patterns: [],
      report: `# Investigation Error\n\nUnable to complete investigation: ${error.message}`,
      apiCallCount: getCallCount(),
      confidence: 'INSUFFICIENT',
    };
  }
}

function extractConnections(payload: any): Connection[] {
  if (!payload || payload.error) return [];

  if (Array.isArray(payload.connections)) return payload.connections;
  if (Array.isArray(payload.counterparties)) return payload.counterparties;
  if (Array.isArray(payload.data)) return payload.data;
  if (Array.isArray(payload)) return payload;

  return [];
}

function extractFundingSource(payload: any): FundingSource | null {
  if (!payload || payload.error) return null;

  if (payload.funderAddress) {
    return payload as FundingSource;
  }

  if (payload.funder_address) {
    return {
      funderAddress: payload.funder_address,
      funderNetwork: payload.funder_network || payload.network,
      amountUSD: payload.amountUSD || payload.amount_usd,
      amount: payload.amount,
    };
  }

  // Do not infer funder from generic address fields; this creates false self-funding.
  return null;
}

/**
 * Calculate confidence level based on available data
 */
function calculateConfidence(
  risk: any,
  sanctions: any,
  stats: any
): 'HIGH' | 'MEDIUM' | 'LOW' | 'INSUFFICIENT' {
  // Check for errors or missing data
  if (risk.error || sanctions.error) {
    return 'INSUFFICIENT';
  }

  // High confidence: Clear risk signal or clearly clean
  if (risk.riskLevel === 'CRITICAL' || risk.riskLevel === 'HIGH' || sanctions.isSanctioned) {
    return 'HIGH';
  }

  if (risk.riskLevel === 'VERY_LOW' && !sanctions.isSanctioned && stats && stats.transactionCount > 10) {
    return 'HIGH';
  }

  // Medium confidence: Mixed signals
  if (risk.riskLevel === 'MEDIUM') {
    return 'MEDIUM';
  }

  // Low confidence: Limited data
  if (!stats || stats.transactionCount < 5) {
    return 'LOW';
  }

  return 'MEDIUM';
}
